// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package user

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type RegistUserMessage struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegistUserMessage) Reset()         { *m = RegistUserMessage{} }
func (m *RegistUserMessage) String() string { return proto.CompactTextString(m) }
func (*RegistUserMessage) ProtoMessage()    {}
func (*RegistUserMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *RegistUserMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegistUserMessage.Unmarshal(m, b)
}
func (m *RegistUserMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegistUserMessage.Marshal(b, m, deterministic)
}
func (m *RegistUserMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegistUserMessage.Merge(m, src)
}
func (m *RegistUserMessage) XXX_Size() int {
	return xxx_messageInfo_RegistUserMessage.Size(m)
}
func (m *RegistUserMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_RegistUserMessage.DiscardUnknown(m)
}

var xxx_messageInfo_RegistUserMessage proto.InternalMessageInfo

func (m *RegistUserMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type RegistUserResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegistUserResponse) Reset()         { *m = RegistUserResponse{} }
func (m *RegistUserResponse) String() string { return proto.CompactTextString(m) }
func (*RegistUserResponse) ProtoMessage()    {}
func (*RegistUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *RegistUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegistUserResponse.Unmarshal(m, b)
}
func (m *RegistUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegistUserResponse.Marshal(b, m, deterministic)
}
func (m *RegistUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegistUserResponse.Merge(m, src)
}
func (m *RegistUserResponse) XXX_Size() int {
	return xxx_messageInfo_RegistUserResponse.Size(m)
}
func (m *RegistUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegistUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegistUserResponse proto.InternalMessageInfo

func (m *RegistUserResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetUserMessage struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserMessage) Reset()         { *m = GetUserMessage{} }
func (m *GetUserMessage) String() string { return proto.CompactTextString(m) }
func (*GetUserMessage) ProtoMessage()    {}
func (*GetUserMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *GetUserMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserMessage.Unmarshal(m, b)
}
func (m *GetUserMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserMessage.Marshal(b, m, deterministic)
}
func (m *GetUserMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserMessage.Merge(m, src)
}
func (m *GetUserMessage) XXX_Size() int {
	return xxx_messageInfo_GetUserMessage.Size(m)
}
func (m *GetUserMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserMessage.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserMessage proto.InternalMessageInfo

func (m *GetUserMessage) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type GetUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserResponse) Reset()         { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()    {}
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *GetUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResponse.Unmarshal(m, b)
}
func (m *GetUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResponse.Marshal(b, m, deterministic)
}
func (m *GetUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResponse.Merge(m, src)
}
func (m *GetUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserResponse.Size(m)
}
func (m *GetUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResponse proto.InternalMessageInfo

func (m *GetUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type IncrUserCounterMessage struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IncrUserCounterMessage) Reset()         { *m = IncrUserCounterMessage{} }
func (m *IncrUserCounterMessage) String() string { return proto.CompactTextString(m) }
func (*IncrUserCounterMessage) ProtoMessage()    {}
func (*IncrUserCounterMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *IncrUserCounterMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IncrUserCounterMessage.Unmarshal(m, b)
}
func (m *IncrUserCounterMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IncrUserCounterMessage.Marshal(b, m, deterministic)
}
func (m *IncrUserCounterMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IncrUserCounterMessage.Merge(m, src)
}
func (m *IncrUserCounterMessage) XXX_Size() int {
	return xxx_messageInfo_IncrUserCounterMessage.Size(m)
}
func (m *IncrUserCounterMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_IncrUserCounterMessage.DiscardUnknown(m)
}

var xxx_messageInfo_IncrUserCounterMessage proto.InternalMessageInfo

func (m *IncrUserCounterMessage) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type IncrUserCounterResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IncrUserCounterResponse) Reset()         { *m = IncrUserCounterResponse{} }
func (m *IncrUserCounterResponse) String() string { return proto.CompactTextString(m) }
func (*IncrUserCounterResponse) ProtoMessage()    {}
func (*IncrUserCounterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{6}
}

func (m *IncrUserCounterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IncrUserCounterResponse.Unmarshal(m, b)
}
func (m *IncrUserCounterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IncrUserCounterResponse.Marshal(b, m, deterministic)
}
func (m *IncrUserCounterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IncrUserCounterResponse.Merge(m, src)
}
func (m *IncrUserCounterResponse) XXX_Size() int {
	return xxx_messageInfo_IncrUserCounterResponse.Size(m)
}
func (m *IncrUserCounterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IncrUserCounterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IncrUserCounterResponse proto.InternalMessageInfo

type DecrUserCounterMessage struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DecrUserCounterMessage) Reset()         { *m = DecrUserCounterMessage{} }
func (m *DecrUserCounterMessage) String() string { return proto.CompactTextString(m) }
func (*DecrUserCounterMessage) ProtoMessage()    {}
func (*DecrUserCounterMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{7}
}

func (m *DecrUserCounterMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DecrUserCounterMessage.Unmarshal(m, b)
}
func (m *DecrUserCounterMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DecrUserCounterMessage.Marshal(b, m, deterministic)
}
func (m *DecrUserCounterMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DecrUserCounterMessage.Merge(m, src)
}
func (m *DecrUserCounterMessage) XXX_Size() int {
	return xxx_messageInfo_DecrUserCounterMessage.Size(m)
}
func (m *DecrUserCounterMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_DecrUserCounterMessage.DiscardUnknown(m)
}

var xxx_messageInfo_DecrUserCounterMessage proto.InternalMessageInfo

func (m *DecrUserCounterMessage) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type DecrUserCounterResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DecrUserCounterResponse) Reset()         { *m = DecrUserCounterResponse{} }
func (m *DecrUserCounterResponse) String() string { return proto.CompactTextString(m) }
func (*DecrUserCounterResponse) ProtoMessage()    {}
func (*DecrUserCounterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{8}
}

func (m *DecrUserCounterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DecrUserCounterResponse.Unmarshal(m, b)
}
func (m *DecrUserCounterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DecrUserCounterResponse.Marshal(b, m, deterministic)
}
func (m *DecrUserCounterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DecrUserCounterResponse.Merge(m, src)
}
func (m *DecrUserCounterResponse) XXX_Size() int {
	return xxx_messageInfo_DecrUserCounterResponse.Size(m)
}
func (m *DecrUserCounterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DecrUserCounterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DecrUserCounterResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*User)(nil), "User")
	proto.RegisterType((*RegistUserMessage)(nil), "RegistUserMessage")
	proto.RegisterType((*RegistUserResponse)(nil), "RegistUserResponse")
	proto.RegisterType((*GetUserMessage)(nil), "GetUserMessage")
	proto.RegisterType((*GetUserResponse)(nil), "GetUserResponse")
	proto.RegisterType((*IncrUserCounterMessage)(nil), "IncrUserCounterMessage")
	proto.RegisterType((*IncrUserCounterResponse)(nil), "IncrUserCounterResponse")
	proto.RegisterType((*DecrUserCounterMessage)(nil), "DecrUserCounterMessage")
	proto.RegisterType((*DecrUserCounterResponse)(nil), "DecrUserCounterResponse")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 283 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x41, 0x4b, 0xfb, 0x40,
	0x10, 0xc5, 0x93, 0xfc, 0xf3, 0x6f, 0xf1, 0x15, 0x1a, 0x1d, 0xc1, 0xa4, 0x39, 0x95, 0x45, 0xb0,
	0x8a, 0x0c, 0x58, 0x0f, 0x7e, 0x00, 0x45, 0xe9, 0xc1, 0x4b, 0xc4, 0xb3, 0xd4, 0x66, 0x28, 0x39,
	0x98, 0x94, 0x6c, 0xea, 0x47, 0xf0, 0x73, 0xcb, 0x2e, 0x6d, 0x6a, 0xb7, 0x2d, 0xe8, 0x6d, 0x77,
	0xe6, 0xcd, 0x7b, 0x3b, 0x3f, 0x16, 0x58, 0x6a, 0xa9, 0x79, 0x51, 0x57, 0x4d, 0xa5, 0xae, 0x10,
	0xbe, 0x6a, 0xa9, 0xa9, 0x8f, 0xa0, 0xc8, 0x13, 0x7f, 0xe8, 0x8f, 0xfe, 0x65, 0x41, 0x91, 0x13,
	0x21, 0x2c, 0xa7, 0x1f, 0x92, 0x04, 0x43, 0x7f, 0x74, 0x94, 0xd9, 0xb3, 0xba, 0xc0, 0x49, 0x26,
	0xf3, 0x42, 0x37, 0x66, 0xe2, 0x59, 0xb4, 0x9e, 0xce, 0xa5, 0x15, 0xfa, 0x3f, 0x84, 0xe7, 0xa0,
	0x8d, 0x30, 0x13, 0xbd, 0xa8, 0x4a, 0x2d, 0x6e, 0x84, 0xba, 0x44, 0xff, 0x49, 0xb6, 0xbc, 0x62,
	0x74, 0xcd, 0xd3, 0xde, 0x5a, 0x59, 0xc7, 0x5c, 0x27, 0xb9, 0xba, 0x46, 0xb4, 0x92, 0xb6, 0x6e,
	0x03, 0x84, 0xa6, 0x69, 0x85, 0xbd, 0xf1, 0x7f, 0xb6, 0x4d, 0x5b, 0x52, 0x37, 0x38, 0x9b, 0x94,
	0xb3, 0xda, 0x54, 0xee, 0xab, 0x65, 0xd9, 0xfc, 0x22, 0x60, 0x80, 0xd8, 0x19, 0x59, 0x07, 0x19,
	0xb7, 0x07, 0xf9, 0xb3, 0x9b, 0x33, 0xb2, 0x76, 0x1b, 0x7f, 0x05, 0xe8, 0x99, 0xfa, 0x8b, 0xd4,
	0x9f, 0xc5, 0x4c, 0xe8, 0x0e, 0xd8, 0xa0, 0x22, 0xe2, 0x1d, 0xc0, 0xe9, 0x29, 0xef, 0xb2, 0x54,
	0x1e, 0x31, 0xba, 0x2b, 0x24, 0x14, 0xf1, 0x36, 0xc7, 0xf4, 0x98, 0x1d, 0x5a, 0xca, 0xa3, 0x47,
	0x44, 0xce, 0x86, 0x14, 0xf3, 0x7e, 0x4c, 0x69, 0xc2, 0x87, 0x60, 0x58, 0x1f, 0x67, 0x37, 0x8a,
	0x79, 0x3f, 0xa0, 0x34, 0xe1, 0x03, 0x18, 0x94, 0xf7, 0xde, 0xb1, 0xff, 0xef, 0xf6, 0x3b, 0x00,
	0x00, 0xff, 0xff, 0x4a, 0x2c, 0x6c, 0x2d, 0x8d, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	RegistUser(ctx context.Context, in *RegistUserMessage, opts ...grpc.CallOption) (*RegistUserResponse, error)
	GetUser(ctx context.Context, in *GetUserMessage, opts ...grpc.CallOption) (*GetUserResponse, error)
	IncrUserCounter(ctx context.Context, in *IncrUserCounterMessage, opts ...grpc.CallOption) (*IncrUserCounterResponse, error)
	DecrUserCounter(ctx context.Context, in *DecrUserCounterMessage, opts ...grpc.CallOption) (*DecrUserCounterResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) RegistUser(ctx context.Context, in *RegistUserMessage, opts ...grpc.CallOption) (*RegistUserResponse, error) {
	out := new(RegistUserResponse)
	err := c.cc.Invoke(ctx, "/UserService/RegistUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUser(ctx context.Context, in *GetUserMessage, opts ...grpc.CallOption) (*GetUserResponse, error) {
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, "/UserService/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) IncrUserCounter(ctx context.Context, in *IncrUserCounterMessage, opts ...grpc.CallOption) (*IncrUserCounterResponse, error) {
	out := new(IncrUserCounterResponse)
	err := c.cc.Invoke(ctx, "/UserService/IncrUserCounter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DecrUserCounter(ctx context.Context, in *DecrUserCounterMessage, opts ...grpc.CallOption) (*DecrUserCounterResponse, error) {
	out := new(DecrUserCounterResponse)
	err := c.cc.Invoke(ctx, "/UserService/DecrUserCounter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	RegistUser(context.Context, *RegistUserMessage) (*RegistUserResponse, error)
	GetUser(context.Context, *GetUserMessage) (*GetUserResponse, error)
	IncrUserCounter(context.Context, *IncrUserCounterMessage) (*IncrUserCounterResponse, error)
	DecrUserCounter(context.Context, *DecrUserCounterMessage) (*DecrUserCounterResponse, error)
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_RegistUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistUserMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).RegistUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UserService/RegistUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).RegistUser(ctx, req.(*RegistUserMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UserService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUser(ctx, req.(*GetUserMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_IncrUserCounter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncrUserCounterMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).IncrUserCounter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UserService/IncrUserCounter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).IncrUserCounter(ctx, req.(*IncrUserCounterMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_DecrUserCounter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecrUserCounterMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DecrUserCounter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UserService/DecrUserCounter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DecrUserCounter(ctx, req.(*DecrUserCounterMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegistUser",
			Handler:    _UserService_RegistUser_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _UserService_GetUser_Handler,
		},
		{
			MethodName: "IncrUserCounter",
			Handler:    _UserService_IncrUserCounter_Handler,
		},
		{
			MethodName: "DecrUserCounter",
			Handler:    _UserService_DecrUserCounter_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
